### ISSUE TITLE
Cross reference Emacs+pass projects

### ISSUE THREAD

**Issue by DamienCassou** [jabranham/helm-pass#6]
Emacs already has several pass-related packages. I propose we cross-reference each of them on each package and even Emacs wiki:
- [auth-password-store](https://github.com/DamienCassou/auth-password-store): Integrate Emacs' auth-source with password-store
- [pass](https://github.com/NicolasPetton/pass): major mode for password-store
- [password-store](https://git.zx2c4.com/password-store/tree/contrib/emacs/password-store.el): Password store (pass) support

What do you think?

/cc @NicolasPetton

**Comment by NicolasPetton** [comment]
Agreed!

**Comment by jabranham** [comment]
Sure thing! I'll mention them in the README and commentary section of
helm-pass.el

**Comment by DamienCassou** [comment]
Same for me https://github.com/DamienCassou/auth-password-store/pull/15
